#!/usr/bin/env node
/**
 * wire-skills.cjs — register every .agents/skills/<name>/SKILL.md into .codex/config.toml
 * as a `skills.config` inline array, so native Codex CLI discovers them project-level.
 *
 * Codex schema (verified — developers.openai.com/codex/config-reference):
 *   skills.config = [ { path = "<dir-with-SKILL.md>", enabled = true }, ... ]
 *
 * Path convention: repo-root-relative (config is committed; absolute paths aren't portable).
 * Idempotent: strips any prior `skills.config = [...]` block before re-appending.
 *
 * Usage: node .codex/scripts/wire-skills.cjs [--check]
 *   --check : print the would-be array + count, do NOT write.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..', '..');
const skillsDir = path.join(repoRoot, '.agents', 'skills');
const configPath = path.join(repoRoot, '.codex', 'config.toml');
const checkOnly = process.argv.includes('--check');

function listSkillDirs() {
  return fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((name) => fs.existsSync(path.join(skillsDir, name, 'SKILL.md')))
    .sort();
}

function buildSkillsBlock(names) {
  // Codex (0.137-alpha) requires ABSOLUTE paths for skills.config.path — a relative
  // path fails with "AbsolutePathBuf deserialized without a base path". Paths are
  // regenerated per-machine by re-running this script (forward slashes for TOML).
  const entries = names
    .map((name) => {
      const abs = path.join(skillsDir, name).replace(/\\/g, '/');
      return `  { path = "${abs}", enabled = true },`;
    })
    .join('\n');
  return `skills.config = [\n${entries}\n]`;
}

function stripExistingBlock(toml) {
  // remove the generator comment + multi-line `skills.config = [ ... ]` (inline array of tables)
  return toml
    .replace(/^# Registered skills \(generated[^\n]*\n/m, '')
    .replace(/\n?skills\.config\s*=\s*\[[\s\S]*?\]\s*/m, '\n');
}

function main() {
  if (!fs.existsSync(skillsDir)) {
    console.error(`[wire-skills] missing ${skillsDir}`);
    process.exit(1);
  }
  const names = listSkillDirs();
  const block = buildSkillsBlock(names);

  if (checkOnly) {
    console.log(block);
    console.log(`\n[wire-skills] ${names.length} skills`);
    return;
  }

  let toml = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '';
  toml = stripExistingBlock(toml).replace(/^\s+/, '');
  // Dotted top-level keys (skills.config) MUST precede any [table] header,
  // else TOML nests them under the preceding table (e.g. features.skills.config).
  const header = `# Registered skills (generated by .codex/scripts/wire-skills.cjs — do not hand-edit).\n${block}\n\n`;
  fs.writeFileSync(configPath, header + toml);
  console.log(`[wire-skills] wrote ${names.length} skills into ${path.relative(repoRoot, configPath)}`);
}

main();
